feat: Add new properties class corresponding to .properties file, cha…
aquaMara/Crochet_RegistrationService pull request #4
Opened 2022-08-23 10:36 UTC by aquaMara

2022-08-23 11:24 UTC, anton-bulavko requested changes

2022-08-23 11:24 UTC, anton-bulavko commented on src/main/java/org/aquam/registrationservice/config/ApplicationConfiguration.java
> +
зачем тут 3 пустые линии? удали их, за форматированием кода следить тоже нужно)

2022-08-23 11:24 UTC, anton-bulavko commented on src/main/java/org/aquam/registrationservice/config/ApplicationProperties.java
> +public class ApplicationProperties {
отдельный класс можно и не создавать, а просто инжектить нужное значение в конкретном классе (но не обязательно)

2022-08-23 11:24 UTC, anton-bulavko commented on src/main/java/org/aquam/registrationservice/config/ApplicationProperties.java
> +    private String EMAIL_API_BASE_URL;
EMAIL_API_BASE_URL - такое имя переменных используется для private final static полей, поменять имена нужно

2022-08-23 13:18 UTC, aquaMara commented on src/main/java/org/aquam/registrationservice/config/ApplicationConfiguration.java
> +
Убрала, теперь 0

2022-08-23 13:19 UTC, aquaMara commented on src/main/java/org/aquam/registrationservice/config/ApplicationProperties.java
> +    private String EMAIL_API_BASE_URL;
Поменяла

2022-08-23 13:20 UTC, aquaMara commented on src/main/java/org/aquam/registrationservice/config/ApplicationProperties.java
> +public class ApplicationProperties {
Подумала, что так будет удобнее, поэтому вынесла всё из application.properties в один класс, поняла, что можно добавлять эти значения прямо в нужные классы, спасибо

2022-08-24 09:58 UTC, anton-bulavko approved these changes

2022-08-24 10:23 UTC, merged