feat: Add @Scheduled mthod to delete all unconfirmed accounts, change…
aquaMara/Crochet_RegistrationService pull request #5
Opened 2022-08-23 10:45 UTC by aquaMara

…d logic for registration

2022-08-24 09:57 UTC, anton-bulavko requested changes

2022-08-24 09:57 UTC, anton-bulavko commented on src/main/java/org/aquam/registrationservice/service/impl/RegistrationServiceImpl.java
> +    public String register(RegistrationRequest registrationRequest) {
большой метод, разбить на несколько до 10 строк

2022-08-24 09:57 UTC, anton-bulavko commented on src/main/java/org/aquam/registrationservice/service/impl/RegistrationServiceImpl.java
> +    public String confirmRegistration(String confirmationSequence) {
очень большой метод, разбить на несколько

2022-08-24 09:57 UTC, anton-bulavko commented on src/main/java/org/aquam/registrationservice/service/impl/RegistrationServiceImpl.java
> +}
![Screenshot 2022-08-24 at 12 56 53](https://user-images.githubusercontent.com/50584138/186389603-a7d3b227-cd1f-4ede-9387-f7b9e6b03d3a.png)
добавляй пустую строку в конце любого файла, чтобы гитхаб не ругался

2022-08-24 11:08 UTC, aquaMara commented on src/main/java/org/aquam/registrationservice/service/impl/RegistrationServiceImpl.java
> +}
Добавила

2022-09-02 07:24 UTC, anton-bulavko approved these changes

2022-09-03 15:19 UTC, merged