refactor: Add logic for confirmation of registration
aquaMara/Crochet_RegistrationService pull request #6
Opened 2022-08-23 10:50 UTC by aquaMara

2022-08-24 09:55 UTC, anton-bulavko requested changes

2022-08-24 09:55 UTC, anton-bulavko commented on src/main/java/org/aquam/registrationservice/service/impl/RegistrationConfirmationServiceImpl.java
> +    public String sendConfirmationSequence(Long id, String email) {
большой метод, в идеале разбить на несколько не больше 10 строк

2022-08-24 09:55 UTC, anton-bulavko commented on src/main/java/org/aquam/registrationservice/model/ConfirmationData.java
> +@Data
вроде бы аннотация value включает в себя все, что ты перечислила

2022-08-24 10:54 UTC, aquaMara commented on src/main/java/org/aquam/registrationservice/model/ConfirmationData.java
> +@Data
Поменяла, написано, что она делает все поля final и убирает сеттеры - класс immutable

2022-08-24 11:01 UTC, aquaMara commented on src/main/java/org/aquam/registrationservice/service/impl/RegistrationConfirmationServiceImpl.java
> +    public String sendConfirmationSequence(Long id, String email) {
Разбила, второй метод 12 строк - обращение к email-service, потому что там try-catch с исключениями, но я потом упорядочу и буду выбрасывать те исключения, которые мне нужны

2022-09-02 07:25 UTC, anton-bulavko requested changes

2022-09-02 07:25 UTC, anton-bulavko commented on src/main/java/org/aquam/registrationservice/service/impl/RegistrationConfirmationServiceImpl.java
> +            System.out.println("Could not connect to Email server, check the connection");
никаких sout, нужно подключить логгер и все исключения логгировать

2022-09-03 17:22 UTC, aquaMara commented on src/main/java/org/aquam/registrationservice/service/impl/RegistrationConfirmationServiceImpl.java
> +            System.out.println("Could not connect to Email server, check the connection");
Подключила

2022-09-07 07:26 UTC, anton-bulavko approved these changes

2022-09-07 11:48 UTC, merged