feat: Add exception handler
aquaMara/Crochet_RegistrationService pull request #7
Opened 2022-08-23 10:53 UTC by aquaMara

2022-08-24 09:54 UTC, anton-bulavko requested changes

2022-08-24 09:54 UTC, anton-bulavko commented on src/main/java/org/aquam/registrationservice/exception/AppExceptionHandler.java
> +        return new ResponseEntity<>(response, HttpStatus.BAD_REQUEST);
если статус одинаковый, то ошибки можно передавать массивом в @ExceptionHandler({exception1, exception2, etc})

2022-08-24 09:54 UTC, anton-bulavko commented on src/main/java/org/aquam/registrationservice/exception/AppResponse.java
> +    private Set<ConstraintViolation<?>> validationExceptions;
можно сделать Private final и добавить requiredArgsConstructor над классом

2022-08-24 09:54 UTC, anton-bulavko commented on src/main/java/org/aquam/registrationservice/exception/AppResponse.java
> +    public String getMessage() {
можно использовать аннотацию getter

2022-08-24 10:29 UTC, aquaMara commented on src/main/java/org/aquam/registrationservice/exception/AppExceptionHandler.java
> +        return new ResponseEntity<>(response, HttpStatus.BAD_REQUEST);
Переделала

2022-08-24 10:39 UTC, aquaMara commented on src/main/java/org/aquam/registrationservice/exception/AppExceptionHandler.java
> +        return new ResponseEntity<>(response, HttpStatus.BAD_REQUEST);
но ConstraintViolationException всё равно в отдельном методе

2022-08-24 10:40 UTC, aquaMara commented on src/main/java/org/aquam/registrationservice/exception/AppResponse.java
> +    private Set<ConstraintViolation<?>> validationExceptions;
Сделала, но Set<ConstraintViolation<?>> validationExceptions мне нужны только для ConstraintViolationException, поэтому оно не всегда должно быть в конструкторе. Не делала его final, сделала @RequiredArgsConstructor + @AllArgsConstructor, так можно?

2022-08-24 10:40 UTC, aquaMara commented on src/main/java/org/aquam/registrationservice/exception/AppResponse.java
> +    public String getMessage() {
Переделала

2022-09-02 07:26 UTC, anton-bulavko requested changes

2022-09-02 07:26 UTC, anton-bulavko commented on src/main/java/org/aquam/registrationservice/exception/AppExceptionHandler.java
> +
вот эти пустые линии убери

2022-09-02 07:26 UTC, anton-bulavko commented on src/main/java/org/aquam/registrationservice/exception/AppResponse.java
> +    private Set<ConstraintViolation<?>> validationExceptions;
можно

2022-09-03 15:20 UTC, aquaMara commented on src/main/java/org/aquam/registrationservice/exception/AppResponse.java
> +    private Set<ConstraintViolation<?>> validationExceptions;
Поняла, спасибо

2022-09-03 15:22 UTC, aquaMara commented on src/main/java/org/aquam/registrationservice/exception/AppExceptionHandler.java
> +
Убрала

2022-09-07 07:27 UTC, anton-bulavko approved these changes

2022-09-07 11:48 UTC, merged